title: Noh Jungmin
logo: /assets/img/profile.jpg
email: lumill925@gmail.com
description: 주니어 개발자
favicon: true
color-scheme: auto

plugins:
  - jekyll-sitemap
  - jekyll-seo-tag
  - jemoji

platforms:
  - name: GitHub
    icon: <i class="fa-brands fa-github"></i>
    link: https://github.com/lumill925

navigation:
  - name: Readme
    link: ./README.md
    sublist:
      - name: Image
        link: ./index.html#small-image
  - name: Another Page
    link: ./another-page.html
